config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {:registrations => 'registrations'}
  devise_scope :user do
    get "/register" => "registrations#new"
  end

  resources :cohabitants do
    collection do
      get "personal"
      get "horoscop"
      get "educational"
      get "family"
      get "expectation"
      
      post "save_personal"
      post "save_horoscop"
      post "save_educational"
      post "save_family"
      post "save_expectation"
    end
  end
  
  get "about" => "home#about"
  get "search" => "home#search"
  get "contact" => "home#contact"
  root 'home#index'

end

app/models/cohabitant.rb
class Cohabitant < ActiveRecord::Base
  has_one :cohabitant_family
  has_one :cohabitant_horoscop
  has_one :cohabitant_education
  has_one :cohabitant_address
  has_one :cohabitant_family
  has_one :cohabitant_expectation
  has_many :photos
  belongs_to :user

  def profile_image
    self.photos.last.try(:image).try(:url) || "/assets/#{self.gender}.jpg"
  end

end

app/controllers/cohabitants_controller.rb
class CohabitantsController < ApplicationController
  before_action :authenticate_user!,  only: [:personal, :save_personal, :horoscop, :educational, :family, :expectation, :save_horoscop, :save_educational, :save_family, :save_expectation]
  
  def index
    @cohabitants = Cohabitant.includes([:cohabitant_education, :cohabitant_family, :cohabitant_horoscop, :cohabitant_expectation, :photos]).all
    if params[:gender].present?
      @cohabitants = @cohabitants.where(gender: params[:gender])
    end
    #if current_user.present?
    #  @cohabitants = @cohabitants.where("user_id not in (?)", [current_user.id] )
    #  
    #end
    @cohabitants = @cohabitants.order("id desc").page(params[:page])
      
  end
  
  def show
    @cohabitant = Cohabitant.includes([:cohabitant_education, :cohabitant_family, :cohabitant_horoscop, :cohabitant_expectation, :photos]).where(id: params[:id]).first
    if @cohabitant
      @self_user = (@cohabitant.user_id == current_user.id) rescue false
    else
      redirect_to root_path
    end
  end

  def new
    
  end

  def personal
    @cohabitant = current_user.cohabitant
    if @cohabitant.present?
    else
      redirect_to root_path
    end
    
  end

  def save_personal
    @cohabitant = current_user.cohabitant
    if @cohabitant.present?
      @cohabitant.update_attributes(personal_params.except(:image))
      if personal_params[:image].present?
        @cohabitant.photos.new({image: personal_params[:image]}).save
      end
      redirect_to "/cohabitants/horoscop"
    else
      redirect_to root_path
    end
  end

  def horoscop
    @cohabitant = current_user.cohabitant
    if @cohabitant.present?
      @horoscope = @cohabitant.build_cohabitant_horoscop if @cohabitant.cohabitant_horoscop.nil?
      @horoscope = @cohabitant.cohabitant_horoscop if @cohabitant.cohabitant_horoscop.present?
    else
      redirect_to root_path
    end
  end

  def save_horoscop
    @cohabitant = current_user.cohabitant
    if @cohabitant.present?
      if @cohabitant.cohabitant_horoscop.nil?
        @cohabitant.build_cohabitant_horoscop(horoscope_params).save
      else
        @cohabitant.cohabitant_horoscop.update_attributes(horoscope_params)
      end
      redirect_to "/cohabitants/educational"
    else
      redirect_to root_path
    end
  end
  
  def educational
    @cohabitant = current_user.cohabitant
    if @cohabitant.present?
      @education = @cohabitant.build_cohabitant_education if @cohabitant.cohabitant_education.nil?
      @education = @cohabitant.cohabitant_education if @cohabitant.cohabitant_education.present?
    else
      redirect_to root_path
    end
  end

  def save_educational
    @cohabitant = current_user.cohabitant
    if @cohabitant.present?
      if @cohabitant.cohabitant_education.nil?
        @education = @cohabitant.build_cohabitant_education(education_params).save
      else
        @education = @cohabitant.cohabitant_education.update_attributes(education_params)
      end
      redirect_to "/cohabitants/family"
    else
      redirect_to root_path
    end
  end
  
  def address
    
  end
  
  def family
    @cohabitant = current_user.cohabitant
    if @cohabitant.present?
      @education = @cohabitant.build_cohabitant_family({has_father: true, has_mother: true}) if @cohabitant.cohabitant_family.nil?

      @education = @cohabitant.cohabitant_family if @cohabitant.cohabitant_family.present?
    else
      redirect_to root_path
    end
  end

  def save_family
    @cohabitant = current_user.cohabitant
    if @cohabitant.present?
      if @cohabitant.cohabitant_family.nil?
        @education = @cohabitant.build_cohabitant_family(family_params).save
      else
        @education = @cohabitant.cohabitant_family.update_attributes(family_params)
      end
      redirect_to "/cohabitants/expectation"
    else
      redirect_to root_path
    end
  end
  
  def expectation
    @cohabitant = current_user.cohabitant
    if @cohabitant.present?
      @expection = @cohabitant.build_cohabitant_expectation if @cohabitant.cohabitant_expectation.nil?

      @expectation = @cohabitant.cohabitant_expectation if @cohabitant.cohabitant_expectation.present?
    else
      redirect_to root_path
    end
  end

  def save_expectation
    @cohabitant = current_user.cohabitant
    if @cohabitant.present?
      if @cohabitant.cohabitant_expectation.nil?
        @expectation = @cohabitant.build_cohabitant_expectation(expectation_params).save
      else
        @expectation = @cohabitant.cohabitant_expectation.update_attributes(expectation_params)
      end
      redirect_to "/cohabitants/#{@cohabitant.id}"
    else
      redirect_to root_path
    end
  end

  protected
  
  def personal_params
    params.require(:cohabitant).permit(:sub_cast, :married_status, :height, :weight, :complexion, :is_physical_disabilities, :spectacles, :physical_disabilities, :lens, :blood_group, :image)
  end
  
  def horoscope_params
    params.require(:cohabitant_horoscop).permit(:rashi, :charan, :nadi, :gan, :birth_place, :birth_time, :mangal, :devak, :nakshtra)
  end

  def education_params
    params.require(:cohabitant_education).permit(:area, :education, :occupation, :occupation_city, :income, :is_income_annua)
  end
  
  def family_params
    params.require(:cohabitant_family).permit(:has_father, :has_mother, :parents_occupation, :brothers, :married_brothers, :sisters, :married_sisters, :surnames_of_relatives, :native_district, :native_taluka, :family_wealth, :mamas_name)
  end

  def expectation_params
    params.require(:cohabitant_expectation).permit(:cities, :mangal, :caste, :age_difference, :min_height, :divorcee, :occupation, :education)
  end
  
end

app/helpers/cohabitants_helper.rb
module CohabitantsHelper
end

app/views/cohabitants/_form_loading.html.erb
<div class="col-sm-12 formLoading">
  
  <div class="col-sm-3 text-center <%= 'red' if ['personal', 'horoscope', 'educational', 'family'].include?(locals[:f]) %>">
    <a href="/cohabitants/personal">Personal</a>
  </div>
  <div class="col-sm-3  text-center <%= 'red' if ['horoscope', 'educational', 'family'].include?(locals[:f]) %>">
    <a href="/cohabitants/horoscop">Horoscope</a>
  </div>
  <div class="col-sm-3 text-center <%= 'red' if ['educational', 'family'].include?(locals[:f]) %>">
    <a href="/cohabitants/educational">Educational</a>
  </div>
  <div class="col-sm-3 text-center <%= 'red' if ['family'].include?(locals[:f]) %>">
    <a href="/cohabitants/family">Family</a>
  </div>
</div>

app/views/cohabitants/educational.html.erb
<div class="grid_3">
  <div class="container">
    <div class="breadcrumb1">
      <ul>
        <a href="<%= root_path %>"><i class="fa fa-home home_1"></i></a>
        <span class="divider">&nbsp;|&nbsp;</span>
        <li class="current-page">Occupational And Educational Details</li>
      </ul>
    </div>
    <%= render "form_loading.html.erb",  locals: {f: "educational" } %>
    <div class="services">
      <%= form_for @education, url: save_educational_cohabitants_path, :method => "post" do |f| %>
	<div class="col-sm-12 padding0">
	  <div class="col-sm-6 paddingL0">
	    <div class="form-group">
	      <label for="cohabitant_education_area">Education Area <span class="form-required" title="This field is required.">*</span></label>
	      <%= f.select :area, options_for_select([ "UNDER GRADUATE", "GRADUATE", "POST GRADUATE", "DOCTOR"], f.object.area || "12 to GRADUATE"), {}, class: "form-select"%>
	    </div>
	  </div>
	  <div class="col-sm-6">
	    <div class="form-group">
	      <label for="cohabitant_education_education">Education <span class="form-required" title="This field is required.">*</span></label>
	      <%= f.text_field :education, autofocus: true , class: "form-text" , maxlength: "20", placeholder: "BE MBA" %>
	    </div>
	  </div>
	</div>
	<div class="col-sm-12 padding0">
	  <div class="col-sm-6 paddingL0">
	    <div class="form-group">
	      <label for="cohabitant_education_occupation">Occupation <span class="form-required" title="This field is required.">*</span></label>
	      <%= f.text_field :occupation, autofocus: true , class: "form-text" , maxlength: "20", placeholder: "Opucation" %>
	    </div>
	  </div>
	  <div class="col-sm-6">
	    <div class="form-group">
	      <label for="cohabitant_education_occupation_city">Occupation City <span class="form-required" title="This field is required.">*</span></label>
	      <%= f.text_field :occupation_city, autofocus: true , class: "form-text" , maxlength: "20", placeholder: "Opucation City" %>

	    </div>
	  </div>
	</div>
	<div class="col-sm-12 padding0">
	  <div class="col-sm-6 paddingL0">
	    <div class="form-group">
	      <label for="cohabitant_education_income">Income <span class="form-required" title="This field is required.">*</span></label>
	      <%= f.text_field :income, autofocus: true , class: "form-text" ,   onkeypress: "return (event.charCode >= 48 && event.charCode <= 57) || event.charCode === 46", maxlength: "10", placeholder: "Income Lacks per annual" %>

	    </div>
	  </div>
	</div>
	<div class="col-sm-12 padding0 ">
	  <div class="form-actions">
	    <input type="submit" id="edit-submit" name="op" value="Next" class="btn_1 submit">
	    <a href="/cohabitants/family" class="skipLink">Skip</a>
	  </div>
	</div>
      <%- end %>
      <div class="clearfix"> </div>
    </div>
  </div>
</div>

app/views/cohabitants/expectation.html.erb
<div class="grid_3">
  <div class="container">
    <div class="breadcrumb1">
      <ul>
        <a href="<%= root_path %>"><i class="fa fa-home home_1"></i></a>
        <span class="divider">&nbsp;|&nbsp;</span>
        <li class="current-page">Expectation Details</li>
      </ul>
    </div>
    <div class="services">
      <%= form_for @expectation, url: save_expectation_cohabitants_path(@cohabitant), :method => "post" do |f| %>
	<div class="col-sm-12 padding0">
	  <div class="col-sm-6 paddingL0">
	    <div class="form-group">
	      <label for="cohabitant_expectation_cities"> Cities<span class="form-required" title="This field is required.">*</span></label>
	      <%= f.text_field :cities, autofocus: true , class: "form-text" , maxlength: "40", placeholder: "CITY" %>
	    </div>
	  </div>
	  <div class="col-sm-6">
	    <div class="form-group">
	      <label for="cohabitant_expectation_mangal">Mangal <Span class="form-required" title="This field is required.">*</span></label>
	      <%= f.select :mangal, options_for_select(["YES", "NO", "SAUMYA", "NIRDOSH", "DOESNT MATTER"], f.object.mangal || "DOESNT MATTER"), {}, class: "form-select"%>
	    </div>
	  </div>
	</div>
	<div class="col-sm-12 padding0">
	  <div class="col-sm-6 paddingL0">
	    <div class="form-group">
	      <label for="cohabitant_expectation_caste"> caste<span class="form-required" title="This field is required.">*</span></label>
	      <%= f.select "caste", options_for_select([ "MARATHA", "96 KULI", "DESHMUKH", "KUNBI", "TIRALE KUNBI" ], f.object.caste || "MARATHA"), {}, class: "form-select"%>
	    </div>
	  </div>
	  <div class="col-sm-6">
	    <div class="form-group">
	      <label for="cohabitant_expectation_age_difference">Age Difference <Span class="form-required" title="This field is required.">*</span></label>
	      <%= f.select :age_difference, options_for_select(["1", "2", "3", "4", "5", "6", "7", "8"], f.object.age_difference || "DOESNT MATTER"), {}, class: "form-select"%>
	    </div>
	  </div>
	</div>

	<div class="col-sm-12 padding0">
	  <div class="col-sm-6 paddingL0">
	    <div class="form-group">
	      <label for="cohabitant_expectation_min_height"> Min Height<span class="form-required" title="This field is required.">*</span></label>
	      <%= f.text_field :min_height, autofocus: true , class: "form-text" , onkeypress: "return (event.charCode >= 48 && event.charCode <= 57) || event.charCode === 46", maxlength: "5", placeholder: "MIN HEIGHT" %>
	    </div>
	  </div>
	  <div class="col-sm-6">
	    <div class="form-group">
	      <label for="cohabitant_expectation_divorcee">Divorcee <Span class="form-required" title="This field is required.">*</span></label>
	      <%= f.select :divorcee, "<option value'=false' #{'selected' unless f.object.divorcee}>No</option><option value='true' #{'selected' if f.object.divorcee}>Yes</option>".html_safe, {}, class: "form-select"%>
	    </div>
	  </div>
	</div>
	
	<div class="col-sm-12 padding0">
	  <div class="col-sm-6 paddingL0">
	    <div class="form-group">
	      <label for="cohabitant_expectation_occupation"> Occupation<span class="form-required" title="This field is required.">*</span></label>
	      <%= f.text_field :occupation, autofocus: true , class: "form-text" , maxlength: "40", placeholder: "OCCUPATION" %>
	    </div>
	  </div>
	  <div class="col-sm-6">
	    <div class="form-group">
	      <label for="cohabitant_expectation_education">Education <Span class="form-required" title="This field is required.">*</span></label>
	      <%= f.text_field :education, autofocus: true , class: "form-text" , maxlength: "40", placeholder: "EDUCATION" %>
	    </div>
	  </div>
	</div>


	<div class="col-sm-12 padding0 ">
	  <div class="form-actions">
	    <input type="submit" id="edit-submit" name="op" value="Finish" class="btn_1 submit">
	  </div>
	</div>
      <%- end %>
      <div class="clearfix"> </div>
    </div>
  </div>
</div>

app/views/cohabitants/family.html.erb
<div class="grid_3">
  <div class="container">
    <div class="breadcrumb1">
      <ul>
        <a href="<%= root_path %>"><i class="fa fa-home home_1"></i></a>
        <span class="divider">&nbsp;|&nbsp;</span>
        <li class="current-page">Family Details</li>
      </ul>
    </div>
    <%= render "form_loading.html.erb", locals: {f: "family" } %>
    <div class="services">
      <%= form_for @education, url: save_family_cohabitants_path, :method => "post" do |f| %>
	<div class="col-sm-12 padding0">
	  <div class="col-sm-3 paddingL0">
	    <div class="form-group">
	      <label for="has_father"> Has Father<span class="form-required" title="This field is required.">*</span></label>
	      <%= f.select :has_father, "<option value'=false' #{'selected' unless f.object.has_father}>No</option><option value='true' #{'selected' if f.object.has_father}>Yes</option>".html_safe, {}, class: "form-select"%>
	    </div>
	  </div>
	  
	  <div class="col-sm-3">
	    <div class="form-group">
	      <label for="has_mother"> Has Mother<span class="form-required" title="This field is required.">*</span></label>
	      <%= f.select :has_mother, "<option value'=false' #{'selected' unless f.object.has_father}>No</option><option value='true' #{'selected' if f.object.has_father}>Yes</option>".html_safe, {}, class: "form-select"%>
	    </div>
	  </div>
	  <div class="col-sm-6 ">
	    <div class="form-group">
	      <label for="cohabitant_family_parents_occupation"> Parents Occupation<span class="form-required" title="This field is required.">*</span></label>
	      <%= f.select :parents_occupation, options_for_select([ "BUSINESS", "PRIVATE SERVICE", "FARMER", "GOVERNMENT SERVICE"], f.object.parents_occupation || "BUSINESS"), {}, class: "form-select"%>
	    </div>
	  </div>
	</div>

	<div class="col-sm-12 padding0">
	  <div class="col-sm-3 paddingL0">
	    <div class="form-group">
	      <label for="cohabitant_family_brothers"> Brothers<span class="form-required" title="This field is required.">*</span></label>
	      <%= f.select :brothers, options_for_select([ "1", "2", "3", "4"], f.object.brothers || "1"), {}, class: "form-select"%>
	    </div>
	  </div>
	  <div class="col-sm-3">
	    <div class="form-group">
	      <label for="cohabitant_family_married_brothers">Married Brothers <Span class="form-required" title="This field is required.">*</span></label>
	      <%= f.select :married_brothers, options_for_select([ "1", "2", "3", "4"], f.object.married_brothers || "1"), {}, class: "form-select"%>
	    </div>
	  </div>
	
	  <div class="col-sm-3">
	    <div class="form-group">
	      <label for="cohabitant_family_sisters"> Sisters<span class="form-required" title="This field is required.">*</span></label>
	      <%= f.select :sisters, options_for_select([ "1", "2", "3", "4"], f.object.sisters || "1"), {}, class: "form-select"%>
	    </div>
	  </div>
	  <div class="col-sm-3">
	    <div class="form-group">
	      <label for="cohabitant_family_married_sisters">Married Sisters <Span class="form-required" title="This field is required.">*</span></label>
	      <%= f.select :married_sisters, options_for_select([ "1", "2", "3", "4"], f.object.married_sisters || "1"), {}, class: "form-select"%>
	    </div>
	  </div>
	</div>

	<div class="col-sm-12 padding0">
	  <div class="col-sm-6 paddingL0">
	  </div>
	  <div class="col-sm-6">
	    <div class="form-group">
	      <label for="cohabitant_family_surnames_of_relatives">Surnames Of Relatives <Span class="form-required" title="This field is required.">*</span></label>
	      <%= f.text_field :surnames_of_relatives, autofocus: true , class: "form-text" , maxlength: "100", placeholder: "Surname Of Relatives ", onkeypress: "return (event.charCode >= 65 && event.charCode <= 90)||(event.charCode >= 97 && event.charCode <= 122) || event.charCode === 44 || event.charCode === 32" %>
	    </div>
	  </div>
	</div>

	<div class="col-sm-12 padding0">
	  <div class="col-sm-6 paddingL0">
	    <div class="form-group">
	      <label for="cohabitant_family_native_district"> Native District<span class="form-required" title="This field is required.">*</span></label>
	      <%= f.text_field :native_district, autofocus: true , class: "form-text" , maxlength: "40", placeholder: "Native District", onkeypress: "return (event.charCode >= 65 && event.charCode <= 90)||(event.charCode >= 97 && event.charCode <= 122) || event.charCode === 44 || event.charCode === 32" %>
	    </div>
	  </div>
	  <div class="col-sm-6">
	    <div class="form-group">
	      <label for="cohabitant_family_native_taluka">Native Taluka <Span class="form-required" title="This field is required.">*</span></label>
	      <%= f.text_field :native_taluka, autofocus: true , class: "form-text" , maxlength: "40", placeholder: "Native Taluka", onkeypress: "return (event.charCode >= 65 && event.charCode <= 90)||(event.charCode >= 97 && event.charCode <= 122) || event.charCode === 44 || event.charCode === 32" %>
	    </div>
	  </div>
	</div>
	<div class="col-sm-12 padding0">
	  <div class="col-sm-6 paddingL0">
	    <div class="form-group">
	      <label for="cohabitant_family_family_wealth"> Family Wealth<span class="form-required" title="This field is required.">*</span></label>
	      <%= f.text_field :family_wealth, autofocus: true , class: "form-text" , maxlength: "40", placeholder: "Family Wealth ", onkeypress: "return (event.charCode >= 65 && event.charCode <= 90)||(event.charCode >= 97 && event.charCode <= 122) || event.charCode === 44 || event.charCode === 32" %>
	    </div>
	  </div>
	  <div class="col-sm-6">
	    <div class="form-group">
	      <label for="cohabitant_family_mamas_name">Mamas Name <Span class="form-required" title="This field is required.">*</span></label>
	      <%= f.text_field :mamas_name, autofocus: true , class: "form-text" , maxlength: "40", placeholder: "Mamas Name ", onkeypress: "return (event.charCode >= 65 && event.charCode <= 90)||(event.charCode >= 97 && event.charCode <= 122) || event.charCode === 44 || event.charCode === 32" %>
	    </div>
	  </div>
	</div>

	<div class="col-sm-12 padding0 ">
	  <div class="form-actions">
	    <input type="submit" id="edit-submit" name="op" value="Next" class="btn_1 submit">
	    <a href="/cohabitants/expectation" class="skipLink">Skip</a>
	  </div>
	</div>
      <%- end %>
      <div class="clearfix"> </div>
    </div>
  </div>
</div>

app/views/cohabitants/horoscop.html.erb
<div class="grid_3">
  <div class="container">
    <div class="breadcrumb1">
      <ul>
        <a href="<%= root_path %>"><i class="fa fa-home home_1"></i></a>
        <span class="divider">&nbsp;|&nbsp;</span>
        <li class="current-page"> Horoscope Details</li>
      </ul>
    </div>
    <%= render "form_loading.html.erb", locals: {f: "horoscope" } %>
    <div class="services">
      <%= form_for @horoscope, url: save_horoscop_cohabitants_path, :method => "post" do |f| %>
	<div class="col-sm-12 padding0">
	  <div class="col-sm-6 paddingL0">
	    <div class="form-group">
	      <label for="cohabitant_horoscop_rashi">Rashi <span class="form-required" title="This field is required.">*</span></label>
	      <%= f.select "rashi", options_for_select([ "MESH", "VRUSHABH", "MITHUN", "KARK", "SINHA", "KANYA", "TULA", "VRISCHIK", "DHANU", "MAKAR", "KUMBH", "MEEN"], f.object.rashi ||"MESH"), {}, class: "form-select"%>
	    </div>
	  </div>
	  <div class="col-sm-6">
	    <div class="form-group">
	      <label for="cohabitant_horoscop_nakshtra">Nakshtra <span class="form-required" title="This field is required.">*</span></label>
	      <%= f.select "nakshtra", options_for_select([ "ASHVINI", "BHARANI", "KRITTIKA", "ROHINI", "MRIGASHĪRSHA", "ARDRA", "PUNARVASU", "PUSHYA" "ĀSHLESHĀ", "MAGHĀ", "PŪRVA PHALGUNĪ", "UTTARA PHALGUNĪ", "HASTA", "CHITRA", "SWĀTI", "VISHAKHA", "ANURADHA", "JYESHTHA", "MULA", "PURVA ASHADHA", "UTTARA ASHADHA", "ABHIJIT", "SRAVANA", "DHANISHTA", "SHATABHISHA", "PURVA BHADRAPADA", "UTTARA BHĀDRAPADĀ", "REVATI" ], f.object.nakshtra || "ASHVINI"), {}, class: "form-select"%>
	    </div>
	  </div>
	</div>
	<div class="col-sm-12 padding0">
	  <div class="col-sm-6 paddingL0">
	    <div class="form-group">
	      <label for="cohabitant_horoscop_charan">Charan <span class="form-required" title="This field is required.">*</span></label>
	      <%= f.select :charan, options_for_select([ "1", "2", "3", "4" ], f.object.charan ||"1"), {}, class: "form-select"%>
	    </div>
	  </div>
	  <div class="col-sm-6">
	    <div class="form-group">
	      <label for="cohabitant_horoscop_nadi">Nadi <span class="form-required" title="This field is required.">*</span></label>
	      <%= f.select :nadi, options_for_select(["ADHYA", "MADHYA", "ANTYA"], f.object.nadi || "ADHYA"), {}, class: "form-select"%>
	    </div>
	  </div>
	</div>
	<div class="col-sm-12 padding0">
	  <div class="col-sm-6 paddingL0">
	    <div class="form-group">
	      <label for="cohabitant_horoscop_gan">Gan <span class="form-required" title="This field is required.">*</span></label>
	      <%= f.select :gan, options_for_select(["DEV GAN", "MANUSHYA GAN", "RAKSHAS GAN"], f.object.gan || "DEV GAN"), {}, class: "form-select"%>
	    </div>
	  </div>
	  <div class="col-sm-6">
	    <div class="form-group">
	      <label for="cohabitant_horoscop_birth_place">Birth Place <span class="form-required" title="This field is required.">*</span></label>
	      <%= f.text_field :birth_place, autofocus: true , class: "form-text" , maxlength: "20", placeholder: "Birth Place" %>
	    </div>
	  </div>
	</div>
	<div class="col-sm-12 padding0">
	  <div class="col-sm-6 paddingL0">
	    <div class="form-group">
	      <label for="cohabitant_horoscop_birth_time">Birth Time <span class="form-required" title="This field is required.">*</span></label>
	      <%= f.text_field :birth_time, autofocus: true , class: "form-text" , maxlength: "20", placeholder: "Birth Time" %>
	    </div>
	  </div>
	  <div class="col-sm-6">
	    <div class="form-group">
	      <label for="cohabitant_horoscop_mangal">Mangal <span class="form-required" title="This field is required.">*</span></label>
	      <%= f.select :mangal, options_for_select(["YES", "NO", "SAUMYA", "NIRDOSH", "NOT KNOWN"], f.object.mangal || "NOT KNOWN"), {}, class: "form-select"%>
	    </div>
	  </div>
	</div>
	<div class="col-sm-12 padding0">
	  <div class="col-sm-6 paddingL0">
	    <div class="form-group">
	      <label for="cohabitant_horoscop_devak">Devak <span class="form-required" title="This field is required.">*</span></label>
	      <%= f.text_field :devak, autofocus: true , class: "form-text" , maxlength: "20", placeholder: "Devak" %>
	    </div>
	  </div>
	</div>
	<div class="col-sm-12 padding0 ">
	  <div class="form-actions">
	    <input type="submit" id="edit-submit" name="op" value="Next" class="btn_1 submit">
	    <a href="/cohabitants/educational" class="skipLink">Skip</a>
	  </div>
	</div>
      <%- end %>
      <div class="clearfix"> </div>
    </div>
  </div>
</div>